#Requires -RunAsAdministrator
<#
.SYNOPSIS
  Generates WireGuard client keys and writes client/wg0.conf (gitignored).

.PARAMETER VpsPublicKey
  Base64 public key from VPS: sudo cat /etc/wireguard/vps_public.key

.EXAMPLE
  .\New-WireGuardClientConfig.ps1 -VpsPublicKey 'AbCdEf...='
#>

param(
    [Parameter(Mandatory = $true)]
    [string] $VpsPublicKey
)

$ErrorActionPreference = 'Stop'

$wg = Join-Path $env:ProgramFiles 'WireGuard\wg.exe'
if (-not (Test-Path $wg)) {
    $wg = Join-Path ${env:ProgramFiles(x86)} 'WireGuard\wg.exe'
}
if (-not (Test-Path $wg)) {
    throw 'wg.exe not found. Run Install-WireGuard.ps1 first.'
}

$repoClient = Resolve-Path (Join-Path $PSScriptRoot '..')
$keyDir = Join-Path $repoClient 'scripts'
$privPath = Join-Path $keyDir 'home_private.key'
$pubPath  = Join-Path $keyDir 'home_public.key'

Write-Host '[*] Generating WireGuard keypair...'
$priv = (& $wg genkey).Trim()
[System.IO.File]::WriteAllText($privPath, $priv)
$pub = ($priv | & $wg pubkey).Trim()
[System.IO.File]::WriteAllText($pubPath, $pub)

$confPath = Join-Path $repoClient 'wg0.conf'
$lines = @(
    '# Generated by New-WireGuardClientConfig.ps1 - do not commit (see .gitignore)'
    '[Interface]'
    'PrivateKey = ' + $priv.Trim()
    'Address = 10.8.0.2/24'
    ''
    '[Peer]'
    'PublicKey = ' + $VpsPublicKey.Trim()
    'AllowedIPs = 10.8.0.0/24'
    'Endpoint = makmillerrust.duckdns.org:51820'
    'PersistentKeepalive = 25'
)
# WireGuard Windows rejects UTF-8 with BOM; Set-Content -Encoding utf8 adds BOM on PS 5.1
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllLines($confPath, $lines, $utf8NoBom)

Write-Host ''
Write-Host '============================================================'
Write-Host ' HOME PC PUBLIC KEY - add this to VPS /etc/wireguard/wg0.conf [Peer]:'
Write-Host ' ' $pub.Trim()
Write-Host '============================================================'
Write-Host ''
Write-Host "[OK] Written: $confPath"
Write-Host ' Next: Import wg0.conf into WireGuard app (Import tunnel from file), then Activate.'
Write-Host ' Then on VPS: sudo wg set wg0 peer' $pub.Trim() 'allowed-ips 10.8.0.2/32'
Write-Host ' Or edit wg0.conf on VPS and: sudo systemctl restart wg-quick@wg0'
